# Generated by Django 5.2.17 on 2026-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="cursor",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="window_end",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="window_start",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
