# Generated by Django 5.2.17 on 2026-09-11 07:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_connection_cursor_syncrun_window_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_updated", models.PositiveBigIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "platform_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="integrations.platformorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-source_updated"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform_order", "source_updated"), name="unique_xgj_revision"
                    )
                ],
            },
        ),
    ]
