# Generated by Django 5.2.17 on 2026-09-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_platformrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformorder",
            name="refund_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformorder",
            name="refund_snapshot",
            field=models.JSONField(default=dict),
        ),
    ]
