# Generated by Django 5.2.17 on 2026-09-14 03:49

import hashlib
import json
import uuid
from datetime import UTC, datetime, time
from zoneinfo import ZoneInfo

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_sync_boundaries(apps, schema_editor):
    Connection = apps.get_model("integrations", "Connection")
    PlatformOrder = apps.get_model("integrations", "PlatformOrder")
    ExternalFactApplication = apps.get_model("integrations", "ExternalFactApplication")
    AuditEvent = apps.get_model("audit", "AuditEvent")
    beijing = ZoneInfo("Asia/Shanghai")

    for connection in Connection.objects.all():
        audit = (
            AuditEvent.objects.filter(action="xgj.connected", object_id=str(connection.pk))
            .order_by("occurred_at")
            .first()
        )
        if audit:
            local_day = audit.occurred_at.astimezone(beijing).date()
            start = datetime.combine(local_day, time.min, tzinfo=beijing).astimezone(UTC)
            connection.first_connected_at = audit.occurred_at
            connection.sync_start_at = start
            connection.sync_start_basis = "AUDIT"
            connection.sync_start_confirmed_at = audit.occurred_at
            connection.sync_start_confirmed_by_id = audit.actor_id
        else:
            connection.enabled = False
            connection.error = "旧实例缺少可信接入日期，请管理员确认自动同步起始日。"
        connection.save()

        for row in PlatformOrder.objects.filter(connection=connection):
            value = row.snapshot.get("order_time")
            created = None
            if type(value) is int and value > 0:
                try:
                    created = datetime.fromtimestamp(value, UTC)
                except (OverflowError, OSError, ValueError):
                    pass
            if not connection.sync_start_at or not created:
                scope = "UNKNOWN"
                reason = "平台订单缺少有效创建时间，未自动纳入经营范围。"
                result = "NEEDS_REVIEW"
                row.needs_review = True
                row.contract_issues = ["缺少有效订单创建时间"]
            elif created < connection.sync_start_at:
                scope = "HISTORICAL"
                reason = "订单创建于接入起始日之前，继续使用历史导入核对。"
                result = "OUT_OF_SCOPE"
                row.needs_review = False
            else:
                scope = "IN_SCOPE"
                reason = "迁移保留既有平台事实；未自动更改库存、履约或现金。"
                result = "LINKED" if row.order_id else "STORED"
                row.needs_review = True
            row.source_created_at = created
            row.scope_status = scope
            row.scope_reason = reason if scope != "IN_SCOPE" else ""
            row.save()
            body = json.dumps(
                row.snapshot,
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
            ).encode()
            ExternalFactApplication.objects.get_or_create(
                connection=connection,
                fact_type="ORDER",
                external_key=row.external_order_no,
                semantic_version=1,
                defaults={
                    "source_updated": row.source_updated,
                    "payload_hash": hashlib.sha256(body).hexdigest(),
                    "result": result,
                    "target_type": "SalesOrder" if row.order_id else "",
                    "target_id": str(row.order_id or ""),
                    "reason": reason,
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        ("integrations", "0004_platformorder_refund_checked_at_and_more"),
        ("orders", "0007_orderitem_order_item_quantity_balance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalFactApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fact_type", models.CharField(max_length=40)),
                ("external_key", models.CharField(max_length=120)),
                ("semantic_version", models.PositiveSmallIntegerField(default=1)),
                ("source_updated", models.PositiveBigIntegerField(default=0)),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("STORED", "已保存待人工处理"),
                            ("LINKED", "已匹配本地记录"),
                            ("OUT_OF_SCOPE", "接入日前历史"),
                            ("NEEDS_REVIEW", "字段待核对"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=40)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("applied_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_refund_no", models.CharField(max_length=120)),
                ("external_order_no", models.CharField(max_length=100)),
                ("source_updated", models.PositiveBigIntegerField(default=0)),
                ("snapshot", models.JSONField(default=dict)),
                ("contract_issues", models.JSONField(default=list)),
                ("needs_review", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-source_updated", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformRefundRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_updated", models.PositiveBigIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-source_updated"],
            },
        ),
        migrations.AddField(
            model_name="connection",
            name="first_connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="sync_start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="sync_start_basis",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="connection",
            name="sync_start_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="sync_start_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="confirmed_sync_starts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="platformorder",
            name="auto_matched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="platformorder",
            name="contract_issues",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="platformorder",
            name="scope_reason",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="platformorder",
            name="scope_status",
            field=models.CharField(
                choices=[
                    ("IN_SCOPE", "自动同步范围内"),
                    ("HISTORICAL", "接入日前历史"),
                    ("UNKNOWN", "范围待核对"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="platformorder",
            name="source_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="accepted_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="historical_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="lease_generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="lease_owner",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="scanned_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="platformorder",
            index=models.Index(
                fields=["connection", "scope_status", "source_updated"],
                name="integration_connect_32a253_idx",
            ),
        ),
        migrations.AddField(
            model_name="externalfactapplication",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="integrations.connection",
            ),
        ),
        migrations.AddField(
            model_name="platformrefund",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="integrations.connection",
            ),
        ),
        migrations.AddField(
            model_name="platformrefund",
            name="platform_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="platform_refunds",
                to="integrations.platformorder",
            ),
        ),
        migrations.AddField(
            model_name="platformrefundrevision",
            name="platform_refund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="integrations.platformrefund",
            ),
        ),
        migrations.AddIndex(
            model_name="externalfactapplication",
            index=models.Index(
                fields=["connection", "result", "source_updated"],
                name="integration_connect_4afe89_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalfactapplication",
            constraint=models.UniqueConstraint(
                fields=("connection", "fact_type", "external_key", "semantic_version"),
                name="unique_external_fact_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformrefund",
            constraint=models.UniqueConstraint(
                fields=("connection", "external_refund_no"), name="unique_platform_refund"
            ),
        ),
        migrations.AddConstraint(
            model_name="platformrefundrevision",
            constraint=models.UniqueConstraint(
                fields=("platform_refund", "source_updated"), name="unique_platform_refund_revision"
            ),
        ),
        migrations.RunPython(backfill_sync_boundaries, noop_reverse),
    ]
