# Generated by Django 5.2.17 on 2026-09-08 01:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0006_salesorder_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("storage_name", models.CharField(max_length=200)),
                ("original_name", models.CharField(max_length=200)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("mime_type", models.CharField(max_length=60)),
                ("active", models.BooleanField(default=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="videos",
                        to="orders.salesorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("order",),
                        name="one_active_order_video",
                    )
                ],
            },
        ),
    ]
