# Generated by Django 5.2.17 on 2026-09-08 01:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntelSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500, unique=True)),
                ("enabled", models.BooleanField(default=False)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntelArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("published", models.CharField(blank=True, max_length=100)),
                (
                    "matched_sku",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.sku",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="insights.intelsource"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("event_date", models.DateField()),
                ("source", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_events",
                        to="catalog.sku",
                    ),
                ),
            ],
            options={
                "ordering": ["event_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price_fen", models.PositiveBigIntegerField()),
                ("observed_on", models.DateField()),
                ("source", models.CharField(max_length=300)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_prices",
                        to="catalog.sku",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_on", "-created_at"],
            },
        ),
    ]
