# Generated by Django 5.2.17 on 2026-09-07 14:40

import uuid

import django.db.models.deletion
from django.db import migrations, models

import app.catalog.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="商品名称")),
                ("brand", models.CharField(blank=True, max_length=100, verbose_name="品牌")),
                ("category", models.CharField(blank=True, max_length=100, verbose_name="分类")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("condition_description", models.TextField(blank=True, verbose_name="货况说明")),
                (
                    "condition_label",
                    models.CharField(blank=True, max_length=100, verbose_name="成色"),
                ),
                (
                    "condition_tags",
                    models.CharField(blank=True, max_length=300, verbose_name="自定义标签"),
                ),
                ("accessories_description", models.TextField(blank=True, verbose_name="配件说明")),
                ("defect_description", models.TextField(blank=True, verbose_name="瑕疵说明")),
                ("function_description", models.TextField(blank=True, verbose_name="功能检测")),
                ("internal_notes", models.TextField(blank=True, verbose_name="内部备注")),
                (
                    "code",
                    models.CharField(
                        default=app.catalog.models.sku_code, max_length=20, unique=True
                    ),
                ),
                (
                    "specification",
                    models.CharField(blank=True, max_length=200, verbose_name="规格"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_explicit_lot_selection", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skus",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
