# Generated by Django 5.2.17 on 2026-09-07 14:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoneyEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=20)),
                ("amount_fen", models.PositiveBigIntegerField()),
                ("reduction_fen", models.PositiveBigIntegerField(default=0)),
                ("reason", models.CharField(max_length=300)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfitSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("net_received_fen", models.BigIntegerField()),
                ("due_fen", models.BigIntegerField()),
                ("cost_fen", models.BigIntegerField()),
                ("fees_fen", models.BigIntegerField()),
                ("recovered_cost_fen", models.BigIntegerField()),
                ("realized_profit_fen", models.BigIntegerField(null=True)),
                ("trigger", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
