# Generated by Django 5.2.17 on 2026-09-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneyentry",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="money_entries",
                to="orders.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="profitsnapshot",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profit_snapshots",
                to="orders.salesorder",
            ),
        ),
    ]
