# Generated by Django 5.2.17 on 2026-09-14 02:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_cash(apps, schema_editor):
    Money = apps.get_model("finance", "MoneyEntry")
    PurchaseEvent = apps.get_model("procurement", "PurchaseEvent")
    alias = schema_editor.connection.alias
    # The old timestamp was auto_now_add, not evidence of actual payment time.
    Money.objects.using(alias).filter(order__isnull=False, source="LEGACY").update(
        source="LEGACY", occurred_at=None, time_quality="UNKNOWN"
    )
    Money.objects.using(alias).filter(order__isnull=False, kind="RECEIPT").update(direction="IN")
    Money.objects.using(alias).filter(order__isnull=False, kind__in=["REFUND", "FEE"]).update(
        direction="OUT"
    )
    for entry in PurchaseEvent.objects.using(alias).filter(kind__in=["pay", "refund"]).iterator():
        cash, created = Money.objects.using(alias).get_or_create(
            purchase_event_id=entry.pk,
            defaults=dict(
                purchase_id=entry.purchase_id,
                kind="PAYMENT" if entry.kind == "pay" else "REFUND",
                direction="OUT" if entry.kind == "pay" else "IN",
                amount_fen=entry.amount_fen,
                reason=entry.reason,
                source="LEGACY",
                source_ref=str(entry.pk),
                occurred_at=None,
                time_quality="UNKNOWN",
            ),
        )
        if created:
            Money.objects.using(alias).filter(pk=cash.pk).update(created_at=entry.created_at)


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
        ("orders", "0007_orderitem_order_item_quantity_balance_and_more"),
        ("procurement", "0006_legacy_logistics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPaymentFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_fen", models.PositiveBigIntegerField()),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="MANUAL", max_length=16)),
                ("source_ref", models.CharField(max_length=200)),
                ("time_quality", models.CharField(default="UNKNOWN", max_length=16)),
                ("platform_status", models.CharField(blank=True, max_length=100)),
                ("evidence", models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name="moneyentry",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="moneyentry",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "未记录"),
                    ("BANK", "银行卡"),
                    ("ALIPAY", "支付宝"),
                    ("WECHAT", "微信"),
                    ("CASH", "现金"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="moneyentry",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moneyentry",
            name="direction",
            field=models.CharField(
                choices=[("IN", "流入"), ("OUT", "流出")], default="OUT", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="moneyentry",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="money_entries",
                to="procurement.purchase",
            ),
        ),
        migrations.AddField(
            model_name="moneyentry",
            name="purchase_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_entry",
                to="procurement.purchaseevent",
            ),
        ),
        migrations.AddField(
            model_name="moneyentry",
            name="source",
            field=models.CharField(default="LEGACY", max_length=16),
        ),
        migrations.AddField(
            model_name="moneyentry",
            name="source_ref",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="moneyentry",
            name="time_quality",
            field=models.CharField(default="UNKNOWN", max_length=16),
        ),
        migrations.AlterField(
            model_name="moneyentry",
            name="occurred_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moneyentry",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="money_entries",
                to="orders.salesorder",
            ),
        ),
        migrations.RunPython(backfill_cash, migrations.RunPython.noop),
        # Flush PostgreSQL deferred FK checks before adding constraints to updated rows.
        migrations.RunSQL("SET CONSTRAINTS ALL IMMEDIATE", migrations.RunSQL.noop),
        migrations.AddConstraint(
            model_name="moneyentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("order__isnull", False), ("purchase__isnull", True)),
                    models.Q(("order__isnull", True), ("purchase__isnull", False)),
                    _connector="OR",
                ),
                name="money_exactly_one_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="moneyentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("direction", "IN"), ("kind", "RECEIPT"), ("order__isnull", False)),
                    models.Q(
                        ("direction", "OUT"),
                        ("kind__in", ["REFUND", "FEE"]),
                        ("order__isnull", False),
                    ),
                    models.Q(
                        ("direction", "OUT"), ("kind", "PAYMENT"), ("purchase__isnull", False)
                    ),
                    models.Q(("direction", "IN"), ("kind", "REFUND"), ("purchase__isnull", False)),
                    _connector="OR",
                ),
                name="money_kind_direction",
            ),
        ),
        migrations.AddField(
            model_name="customerpaymentfact",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerpaymentfact",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_payments",
                to="orders.salesorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerpaymentfact",
            constraint=models.UniqueConstraint(
                fields=("order", "source", "source_ref"), name="unique_customer_payment_fact"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerpaymentfact",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_fen__gt", 0)), name="customer_payment_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerpaymentfact",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_ref", ""), _negated=True),
                name="customer_payment_source_required",
            ),
        ),
        migrations.AlterField(
            model_name="moneyentry",
            name="source",
            field=models.CharField(default="MANUAL", max_length=16),
        ),
    ]
