# Generated by Django 5.2.17 on 2026-09-14 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_unified_cash"),
        ("orders", "0007_orderitem_order_item_quantity_balance_and_more"),
        ("procurement", "0006_legacy_logistics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="moneyentry",
            index=models.Index(
                fields=["order", "occurred_at"], name="finance_mon_order_i_fb4b56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moneyentry",
            index=models.Index(
                fields=["purchase", "occurred_at"], name="finance_mon_purchas_27b14a_idx"
            ),
        ),
    ]
