# Generated by Django 5.2.17 on 2026-09-07 14:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("condition_description", models.TextField(blank=True, verbose_name="货况说明")),
                (
                    "condition_label",
                    models.CharField(blank=True, max_length=100, verbose_name="成色"),
                ),
                (
                    "condition_tags",
                    models.CharField(blank=True, max_length=300, verbose_name="自定义标签"),
                ),
                ("accessories_description", models.TextField(blank=True, verbose_name="配件说明")),
                ("defect_description", models.TextField(blank=True, verbose_name="瑕疵说明")),
                ("function_description", models.TextField(blank=True, verbose_name="功能检测")),
                ("internal_notes", models.TextField(blank=True, verbose_name="内部备注")),
                (
                    "label",
                    models.CharField(blank=True, max_length=100, verbose_name="这件/这组货的名称"),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=100, verbose_name="来源/供应商"),
                ),
                ("unit_cost_fen", models.PositiveBigIntegerField()),
                ("unit_freight_fen", models.PositiveBigIntegerField(default=0)),
                ("received_qty", models.PositiveIntegerField()),
                ("on_hand_qty", models.PositiveIntegerField()),
                ("reserved_qty", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="catalog.sku",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=40)),
                ("on_hand_delta", models.IntegerField(default=0)),
                ("reserved_delta", models.IntegerField(default=0)),
                ("inspection_delta", models.IntegerField(default=0)),
                ("on_hand_after", models.PositiveIntegerField()),
                ("reserved_after", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=300)),
                ("reference_id", models.CharField(blank=True, max_length=36)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.stocklot"
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.sku"
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("on_hand_qty", models.PositiveIntegerField(default=0)),
                ("reserved_qty", models.PositiveIntegerField(default=0)),
                ("inspection_qty", models.PositiveIntegerField(default=0)),
                (
                    "sku",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance",
                        to="catalog.sku",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("on_hand_qty__gte", models.F("reserved_qty"))),
                        name="balance_reserve_within_stock",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                condition=models.Q(("on_hand_qty__gte", models.F("reserved_qty"))),
                name="lot_reserve_within_stock",
            ),
        ),
    ]
