# Generated by Django 5.2.17 on 2026-09-14 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklot",
            name="last_restocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="origin_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.stocklot",
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="original_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
