# Generated by Django 5.2.17 on 2026-09-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0002_purchase_logistics"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stocklot",
            index=models.Index(
                fields=["sku", "original_received_at"], name="inventory_s_sku_id_c5f644_idx"
            ),
        ),
    ]
