# Generated by Django 5.2.17 on 2026-09-14 02:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_t3(apps, schema_editor):
    Purchase = apps.get_model("procurement", "Purchase")
    SupplyAllocation = apps.get_model("operations", "SupplyAllocation")
    Threshold = apps.get_model("operations", "BottleneckThreshold")
    alias = schema_editor.connection.alias
    for purchase in Purchase.objects.using(alias).exclude(order_item_id=None).iterator():
        SupplyAllocation.objects.using(alias).get_or_create(
            purchase_id=purchase.pk,
            order_item_id=purchase.order_item_id,
            defaults={"quantity": purchase.quantity, "source": "LEGACY"},
        )
    defaults = {"K1": 0, "K2": 0, "K3": 90, "K4": 0, "K5": 0, "K7": 0}
    for kind, days in defaults.items():
        Threshold.objects.using(alias).get_or_create(kind=kind, defaults={"days": days})


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0007_orderitem_order_item_quantity_balance_and_more"),
        ("procurement", "0006_legacy_logistics"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BottleneckThreshold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=4, unique=True)),
                ("days", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommitmentRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_type", models.CharField(max_length=32)),
                ("object_id", models.UUIDField()),
                ("old_due_at", models.DateTimeField(blank=True, null=True)),
                ("new_due_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(max_length=300)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=4)),
                ("object_type", models.CharField(max_length=32)),
                ("object_id", models.UUIDField()),
                ("cycle", models.PositiveIntegerField(default=1)),
                ("first_detected_at", models.DateTimeField()),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-first_detected_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["kind", "resolved_at", "snoozed_until"],
                        name="operations__kind_bba453_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("kind", "object_type", "object_id"),
                        name="one_active_followup_cycle",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ListingMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_listing_id", models.CharField(max_length=200)),
                ("external_spec_id", models.CharField(blank=True, max_length=200)),
                ("listing_url", models.URLField(blank=True, max_length=1000)),
                ("evidence", models.CharField(max_length=300)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shops.saleschannel"
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listing_mappings",
                        to="catalog.sku",
                    ),
                ),
            ],
            options={
                "ordering": ["channel_id", "external_listing_id", "external_spec_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "external_listing_id", "external_spec_id"),
                        name="unique_listing_spec_mapping",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("external_listing_id", ""), _negated=True),
                        name="listing_id_required",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplyAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("source", models.CharField(default="MANUAL", max_length=16)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_allocations",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_allocations",
                        to="procurement.purchase",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("purchase", "order_item"), name="unique_purchase_order_supply"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="supply_qty_positive"
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_t3, migrations.RunPython.noop),
    ]
