# Generated by Django 5.2.17 on 2026-09-08 01:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(blank=True, max_length=200)),
                ("tags", models.CharField(blank=True, max_length=300)),
                ("notes", models.TextField(blank=True)),
                ("risk_reason", models.TextField(blank=True)),
                (
                    "suggestion",
                    models.CharField(
                        choices=[
                            ("NONE", "无建议"),
                            ("PENDING", "售后结束后提醒拉黑"),
                            ("DEFERRED", "暂缓处理"),
                            ("IGNORED", "已忽略建议"),
                            ("DONE", "已自行处理"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
    ]
