# Generated by Django 5.2.17 on 2026-09-07 17:45

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models

import app.procurement.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("condition_description", models.TextField(blank=True, verbose_name="货况说明")),
                (
                    "condition_label",
                    models.CharField(blank=True, max_length=100, verbose_name="成色"),
                ),
                (
                    "condition_tags",
                    models.CharField(blank=True, max_length=300, verbose_name="自定义标签"),
                ),
                ("accessories_description", models.TextField(blank=True, verbose_name="配件说明")),
                ("defect_description", models.TextField(blank=True, verbose_name="瑕疵说明")),
                ("function_description", models.TextField(blank=True, verbose_name="功能检测")),
                ("internal_notes", models.TextField(blank=True, verbose_name="内部备注")),
                (
                    "number",
                    models.CharField(
                        default=app.procurement.models.purchase_number, max_length=20, unique=True
                    ),
                ),
                ("supplier_name", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost_fen", models.PositiveBigIntegerField()),
                ("shipped_qty", models.PositiveIntegerField(default=0)),
                ("received_qty", models.PositiveIntegerField(default=0)),
                ("cancelled_qty", models.PositiveIntegerField(default=0)),
                ("ordered", models.BooleanField(default=False)),
                ("closed", models.BooleanField(default=False)),
                ("paid_fen", models.PositiveBigIntegerField(default=0)),
                ("refunded_fen", models.PositiveBigIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.sku"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="procurement.supplier"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=30)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("amount_fen", models.PositiveBigIntegerField(default=0)),
                ("reason", models.CharField(max_length=300)),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="procurement.purchase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.stocklot"
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="procurement.purchase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("condition_description", models.TextField(blank=True, verbose_name="货况说明")),
                (
                    "condition_label",
                    models.CharField(blank=True, max_length=100, verbose_name="成色"),
                ),
                (
                    "condition_tags",
                    models.CharField(blank=True, max_length=300, verbose_name="自定义标签"),
                ),
                ("accessories_description", models.TextField(blank=True, verbose_name="配件说明")),
                ("defect_description", models.TextField(blank=True, verbose_name="瑕疵说明")),
                ("function_description", models.TextField(blank=True, verbose_name="功能检测")),
                ("internal_notes", models.TextField(blank=True, verbose_name="内部备注")),
                ("unit_cost_fen", models.PositiveBigIntegerField()),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.sku"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="procurement.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="purchase",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="procurement.supplierquote",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="purchase_positive_qty"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "quantity__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("received_qty"), "+", models.F("cancelled_qty")
                        ),
                    )
                ),
                name="purchase_received_within_qty",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("shipped_qty__gte", models.F("received_qty")),
                    ("shipped_qty__lte", models.F("quantity")),
                ),
                name="purchase_shipped_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid_fen__gte", models.F("refunded_fen"))),
                name="purchase_refund_within_paid",
            ),
        ),
    ]
