# Generated by Django 5.2.17 on 2026-09-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="returned_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchaseevent",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="procurement.purchasereceipt",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceipt",
            name="returned_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("received_qty__gte", models.F("returned_qty"))),
                name="purchase_return_within_received",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", models.F("returned_qty"))),
                name="purchase_receipt_return_range",
            ),
        ),
    ]
