# Generated by Django 5.2.17 on 2026-09-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orderitem_specification_snapshot"),
        ("procurement", "0002_purchase_returned_qty_purchaseevent_receipt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="orders.orderitem",
            ),
        ),
    ]
