# Generated by Django 5.2.17 on 2026-09-08 01:32

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0005_returnreceipt_inspection_lot_shipment_evidence_note_and_more"),
        ("procurement", "0003_purchase_order_item"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="purchase",
            name="purchase_received_within_qty",
        ),
        migrations.RemoveConstraint(
            model_name="purchase",
            name="purchase_shipped_range",
        ),
        migrations.AddField(
            model_name="purchase",
            name="direct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchase",
            name="direct_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "quantity__gte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("received_qty"), "+", models.F("cancelled_qty")
                            ),
                            "+",
                            models.F("direct_qty"),
                        ),
                    )
                ),
                name="purchase_received_within_qty",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "shipped_qty__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("received_qty"), "+", models.F("direct_qty")
                        ),
                    ),
                    ("shipped_qty__lte", models.F("quantity")),
                ),
                name="purchase_shipped_range",
            ),
        ),
    ]
