# Generated by Django 5.2.17 on 2026-09-14 01:47

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0007_orderitem_order_item_quantity_balance_and_more"),
        ("procurement", "0004_remove_purchase_purchase_received_within_qty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchDisposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=300)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseArrival",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("inspected_qty", models.PositiveIntegerField(default=0)),
                ("rejected_qty", models.PositiveIntegerField(default=0)),
                ("rejected_returned_qty", models.PositiveIntegerField(default=0)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("customer", models.BooleanField(default=False)),
                ("source", models.CharField(default="MANUAL", max_length=16)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseDispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("received_qty", models.PositiveIntegerField(default=0)),
                ("disposed_qty", models.PositiveIntegerField(default=0)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("expected_arrival_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("carrier", models.CharField(blank=True, max_length=100)),
                ("tracking_no", models.CharField(blank=True, max_length=100)),
                ("customer", models.BooleanField(default=False)),
                ("source", models.CharField(default="MANUAL", max_length=16)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "result",
                    models.CharField(
                        choices=[("ACCEPT", "验收合格"), ("REJECT", "不合格待退供")], max_length=12
                    ),
                ),
                ("inspected_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(max_length=300)),
                ("source", models.CharField(default="MANUAL", max_length=16)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="purchase",
            name="purchase_shipped_range",
        ),
        migrations.AddField(
            model_name="purchase",
            name="legacy_logistics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchase",
            name="promised_dispatch_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="rejected_returned_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipped_qty__lte", models.F("quantity"))),
                name="purchase_dispatched_within_qty",
            ),
        ),
        migrations.AddField(
            model_name="purchasearrival",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arrivals",
                to="procurement.purchase",
            ),
        ),
        migrations.AddField(
            model_name="purchasedispatch",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatches",
                to="procurement.purchase",
            ),
        ),
        migrations.AddField(
            model_name="purchasedispatch",
            name="shipment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.shipment",
            ),
        ),
        migrations.AddField(
            model_name="purchasearrival",
            name="dispatch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arrivals",
                to="procurement.purchasedispatch",
            ),
        ),
        migrations.AddField(
            model_name="dispatchdisposition",
            name="dispatch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispositions",
                to="procurement.purchasedispatch",
            ),
        ),
        migrations.AddField(
            model_name="purchaseinspection",
            name="arrival",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspections",
                to="procurement.purchasearrival",
            ),
        ),
        migrations.AddField(
            model_name="purchaseinspection",
            name="receipt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection",
                to="procurement.purchasereceipt",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedispatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="dispatch_positive_qty"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedispatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "quantity__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("received_qty"), "+", models.F("disposed_qty")
                        ),
                    )
                ),
                name="dispatch_quantity_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasearrival",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="arrival_positive_qty"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasearrival",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", models.F("inspected_qty"))),
                name="arrival_inspection_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasearrival",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("inspected_qty__gte", models.F("rejected_qty")),
                    ("rejected_qty__gte", models.F("rejected_returned_qty")),
                ),
                name="arrival_reject_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchdisposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="disposition_positive_qty"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseinspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="inspection_positive_qty"
            ),
        ),
    ]
