# Generated by Django 5.2.17 on 2026-09-07 14:40

import uuid

import django.db.models.deletion
from django.db import migrations, models

import app.orders.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price_fen", models.PositiveBigIntegerField()),
                ("title_snapshot", models.CharField(max_length=200)),
                ("condition_snapshot", models.JSONField(default=dict)),
                ("reserved_qty", models.PositiveIntegerField(default=0)),
                ("shipped_qty", models.PositiveIntegerField(default=0)),
                (
                    "selected_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.stocklot",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.sku"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("status", models.CharField(default="ACTIVE", max_length=16)),
                ("unit_cost_fen", models.PositiveBigIntegerField()),
                ("unit_freight_fen", models.PositiveBigIntegerField()),
                ("condition_snapshot", models.JSONField(default=dict)),
                ("returned_qty", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.stocklot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("status", models.CharField(default="INSPECTION", max_length=20)),
                ("reason", models.CharField(max_length=300)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="orders.reservation",
                    ),
                ),
                (
                    "restocked_lot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.stocklot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        default=app.orders.models.order_number, max_length=24, unique=True
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="客户称呼/临时标识"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("CONFIRMED", "已确认待备货"),
                            ("SHIPPED", "已发货"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("external_order_no", models.CharField(blank=True, max_length=100)),
                ("platform_paid", models.BooleanField(default=False)),
                ("amount_fen", models.PositiveBigIntegerField()),
                ("amount_reduction_fen", models.PositiveBigIntegerField(default=0)),
                ("received_fen", models.PositiveBigIntegerField(default=0)),
                ("refunded_fen", models.PositiveBigIntegerField(default=0)),
                ("cost_fen", models.PositiveBigIntegerField(default=0)),
                ("fees_fen", models.PositiveBigIntegerField(default=0)),
                ("recovered_cost_fen", models.PositiveBigIntegerField(default=0)),
                ("realized_profit_fen", models.BigIntegerField(blank=True, null=True)),
                ("carrier", models.CharField(blank=True, max_length=100)),
                ("tracking_no", models.CharField(blank=True, max_length=100)),
                ("delivery_method", models.CharField(blank=True, max_length=20)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shops.saleschannel"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="orders.salesorder",
            ),
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="orders.salesorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", models.F("returned_qty"))),
                name="return_within_shipped",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_order_no", ""), _negated=True),
                fields=("channel", "external_order_no"),
                name="unique_channel_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("received_fen__gte", models.F("refunded_fen"))),
                name="refund_within_receipts",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_fen__gte", models.F("amount_reduction_fen"))),
                name="reduction_within_order_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="positive_order_quantity"
            ),
        ),
    ]
