# Generated by Django 5.2.17 on 2026-09-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="specification_snapshot",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
