# Generated by Django 5.2.17 on 2026-09-08 01:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orderitem_specification_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "草稿"),
                    ("CONFIRMED", "已确认待备货"),
                    ("PARTIAL", "部分已发货"),
                    ("SHIPPED", "已发货"),
                    ("COMPLETED", "已完成"),
                    ("CANCELLED", "已取消"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("delivery_method", models.CharField(max_length=20)),
                ("carrier", models.CharField(blank=True, max_length=100)),
                ("tracking_no", models.CharField(blank=True, max_length=100)),
                ("cost_fen", models.PositiveBigIntegerField(default=0)),
                ("fee_fen", models.PositiveBigIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="orders.salesorder",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="orders.shipment",
            ),
        ),
    ]
