# Generated by Django 5.2.17 on 2026-09-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_salesorder_status_shipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cancelled_qty",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
