# Generated by Django 5.2.17 on 2026-09-08 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("orders", "0004_orderitem_cancelled_qty"),
        ("procurement", "0003_purchase_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnreceipt",
            name="inspection_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_returns",
                to="inventory.stocklot",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="evidence_note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="shipment",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="procurement.purchase",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.stocklot",
            ),
        ),
    ]
