# Generated by Django 5.2.17 on 2026-09-08 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("orders", "0005_returnreceipt_inspection_lot_shipment_evidence_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="contacts.customer",
            ),
        ),
    ]
