# Generated by Django 5.2.17 on 2026-09-08 02:01

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        ("orders", "0006_salesorder_customer"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "quantity__gte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("reserved_qty"), "+", models.F("shipped_qty")
                            ),
                            "+",
                            models.F("cancelled_qty"),
                        ),
                    )
                ),
                name="order_item_quantity_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lot__isnull", False),
                    models.Q(("shipment__isnull", False), ("status", "CONSUMED")),
                    _connector="OR",
                ),
                name="reservation_source_present",
            ),
        ),
    ]
