# Generated by Django 5.2.17 on 2026-09-15 15:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integrations", "0005_externalfactapplication_platformrefund_and_more"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("spec", models.CharField(blank=True, max_length=200)),
                ("unit_fen", models.PositiveBigIntegerField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("supplier", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=12)),
                ("supplier", models.CharField(max_length=100)),
                ("snapshot", models.JSONField(default=list)),
                ("stale", models.BooleanField(default=False)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="shops.shop"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=100)),
                ("source", models.CharField(default="API", max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SHIPPING", "待发货"),
                            ("PENDING", "待完成"),
                            ("REFUNDING", "退款处理中"),
                            ("COMPLETED", "已完成"),
                            ("REFUNDED", "已退款"),
                            ("CLOSED", "已关闭"),
                            ("REVIEW", "待核对"),
                            ("UNPAID", "未付款"),
                        ],
                        default="REVIEW",
                        max_length=16,
                    ),
                ),
                ("issue", models.CharField(blank=True, max_length=500)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("spec", models.CharField(blank=True, max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("image", models.URLField(blank=True, max_length=1000)),
                ("paid_fen", models.PositiveBigIntegerField(default=0)),
                ("unit_cost_fen", models.PositiveBigIntegerField(blank=True, null=True)),
                ("cost_version", models.PositiveIntegerField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=100)),
                ("supplier_override", models.BooleanField(default=False)),
                ("receiver", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=1000)),
                ("note", models.CharField(blank=True, max_length=1000)),
                ("waybill", models.CharField(blank=True, max_length=100)),
                ("ordered_at", models.DateTimeField(null=True)),
                ("paid_at", models.DateTimeField(null=True)),
                ("shipped_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("refunded_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(null=True)),
                ("refund_waybill", models.CharField(blank=True, max_length=100)),
                ("refund_note", models.CharField(blank=True, max_length=1000)),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                ("loss_fen", models.PositiveBigIntegerField(default=0)),
                ("loss_at", models.DateTimeField(blank=True, null=True)),
                (
                    "platform",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrations.platformorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workbench.productcost",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="shops.shop"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "paid_at"], name="workbench_t_status_243116_idx"
                    ),
                    models.Index(fields=["completed_at"], name="workbench_t_complet_3643f1_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("shop", "number"), name="wb_trade_unique")
                ],
            },
        ),
    ]
