# Generated by Django 5.2.17 on 2026-09-15 15:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


def seed_current_cost(apps, schema_editor):
    Product = apps.get_model("workbench", "ProductCost")
    Version = apps.get_model("workbench", "CostVersion")
    alias = schema_editor.connection.alias
    for product in Product.objects.using(alias).exclude(unit_fen=None).iterator():
        Version.objects.using(alias).get_or_create(
            product_id=product.pk,
            version=product.version,
            defaults={"unit_fen": product.unit_fen, "effective_at": product.updated_at},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("workbench", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("unit_fen", models.PositiveBigIntegerField()),
                ("effective_at", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="workbench.productcost",
                    ),
                ),
            ],
            options={
                "ordering": ["effective_at", "version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "version"), name="wb_cost_version_unique"
                    )
                ],
            },
        ),
        migrations.RunPython(seed_current_cost, migrations.RunPython.noop),
    ]
