# Generated by Django 5.2.17 on 2026-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workbench", "0002_cost_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="refund_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="refund_type",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="refunded_fen",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
