# Generated by Django 5.2.17 on 2026-09-15 15:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0001_initial"),
        ("workbench", "0003_refund_facts"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_retention_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="shops.shop"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExportImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page", models.PositiveIntegerField()),
                ("storage_name", models.CharField(max_length=200)),
                ("sha256", models.CharField(max_length=64)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="workbench.exportbatch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("batch", "page"), name="wb_export_image_page")
                ],
            },
        ),
    ]
