# Generated by Django 5.2.17 on 2026-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workbench", "0005_reference_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcost",
            name="shipping_note",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="productcost",
            name="supplier_wechat",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trade",
            name="default_shipping_note",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="trade",
            name="platform_note",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="trade",
            name="supplier_wechat",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
