# Generated by Django 5.2.17 on 2026-09-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workbench", "0008_status_change_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcost",
            name="condition",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
