# Generated by Django 5.2.17 on 2026-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workbench", "0009_productcost_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="refund_success_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
