# Generated by Django 5.2.17 on 2026-09-17 07:30

import uuid

import django.db.models.deletion
from django.db import migrations, models

import app.workbench.models


class Migration(migrations.Migration):
    dependencies = [
        ("workbench", "0010_trade_refund_success_confirmed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacesettings",
            name="supplier_base_url",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name="SupplierAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        default=app.workbench.models.supplier_token, max_length=64, unique=True
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access",
                        to="workbench.exportbatch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierDispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("express_code", models.CharField(max_length=100)),
                ("express_name", models.CharField(max_length=100)),
                ("waybill", models.CharField(max_length=100)),
                ("state", models.CharField(default="READY", max_length=16)),
                ("message", models.CharField(blank=True, max_length=300)),
                ("submitted_at", models.DateTimeField(null=True)),
                ("confirmed_at", models.DateTimeField(null=True)),
                (
                    "access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workbench.supplieraccess"
                    ),
                ),
                (
                    "trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch",
                        to="workbench.trade",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("storage_name", models.CharField(max_length=250)),
                ("original_name", models.CharField(max_length=200)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("mime_type", models.CharField(max_length=50)),
                (
                    "access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workbench.supplieraccess"
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_videos",
                        to="workbench.trade",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("trade", "sha256"), name="supplier_video_hash")
                ],
            },
        ),
    ]
