# Generated by Django 5.2.17 on 2026-09-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workbench", "0011_workspacesettings_supplier_base_url_supplieraccess_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("SHIPPING", "待发货"),
                    ("PENDING", "待完成"),
                    ("REFUNDING", "退款处理中"),
                    ("COMPLETED", "已完成"),
                    ("REFUNDED", "已退款"),
                    ("CLOSED", "已关闭"),
                    ("REVIEW", "待核对"),
                    ("UNPAID", "未付款"),
                    ("NONSALE", "非经营订单"),
                ],
                default="REVIEW",
                max_length=16,
            ),
        ),
    ]
